@hostname = http://192.168.1.241
##http://192.168.1.241
##http://localhost
@port = 9200
@host = {{hostname}}:{{port}}
@contentType = application/json

#! 전체 찾기 ====================================

###
GET {{host}}/disaster

###
GET {{host}}/disaster/_search


#! 삭제 =========================================
###
DELETE {{host}}/disaster

###
POST {{host}}/disaster/_delete_by_query
content-Type: {{contentType}}

{
  "query":{
    "match": {
      "_id": "LQkg7XcBuv2C4EH71O71"
    }
  }
}

###

#! index field 생성 =============================
###
PUT {{host}}/disaster
content-Type: {{contentType}}

{
  "settings": {
    "number_of_shards" : 5,
    "number_of_replicas": 1
  },
  "mappings": {
    "properties": {
      "control_number" : {"type" : "integer"},
      "type" : { "type" : "keyword" },
      "name" : { "type" : "keyword" },
      "response_levels" : { "type" : "object" },
      "process": { "type" : "keyword" },
      "task_list" : {"type" : "object"},
      "intro": {"type" : "object"},
      "risk_alert":{"type" : "object"},
      "process_flow" :{"type" : "object"},
      "emergency_contact" : {"type" : "object"},
      "docs_format":{"type" : "object"},
      "revision_history":{"type" : "object"}
    }
  }
}

###

#! doc 추가 ======================================
POST {{host}}/disaster/_doc
content-Type: {{contentType}}

{
  "control_number" : 1,
  "type": "nature",
  "name": "감염병",
  "response_levels": [
    {
      "level" : 1,
      "name" : "징후 감지",
      "situation": "○ 해외신종감염병 발생\n○ 국내(타지자체) 신종감염병 확진자 발생",
      "guideline" : "○ 감시활동(발생동향 모니터링) 강화\n○ 방역대응태세 및 방역 인프라 점검\n* 환자 이송체계, 병상, 보호복, 마스크 등 현황 점검",
      "crisis_alert": ["관심"],
      "tasks":[
        {
          "task_code": "1-1",
          "process_category" : 1
        },
        {
          "task_code": "2-1",
          "process_category" : 2
        },
        {
          "task_code": "2-2",
          "process_category" : 3
        },
        {
          "task_code": "3-2",
          "process_category" : 4
        },
        {
          "task_code": "20-1",
          "process_category" : 1
        },
        {
          "task_code": "6-1",
          "process_category" : 13
        },
        {
          "task_code": "7-5",
          "process_category" : 13
        },
        {
          "task_code": "47-1",
          "process_category" : 13
        }
      ]
    },
    { 
      "level" : 2,
      "name" : "초기 대응",
      "situation": "○ 지자체 내 신종감염병 확진자 발생",
      "guideline" : 
        "○ 상황전파(시·도 재난부서, 보건부서, 유관기관 등)\n○ 초기대응반 현장 출동\n- 의심환자 조치(역학조사, 병원이송, 동선 및 접촉자 파악 등)\n- 시 역학조사관 협조 요청(격리병상 확보 등)\n○ 위기 및 위험관리 커뮤니케이션 준비\n- 언론 브리핑\n- 대시민 콜센터 운영",
      "crisis_alert": ["주의"],
      "tasks":[
        {
          "task_code": "4-1",
          "process_category" : 1
        },
        {
          "task_code": "4-2",
          "process_category" : 1
        },
        {
          "task_code": "5-1",
          "process_category" : 2
        },
        {
          "task_code": "5-2",
          "process_category" : 3
        },
        {
          "task_code": "6-1",
          "process_category" : 5
        },
        {
          "task_code": "7-5",
          "process_category" : 1
        },
        {
          "task_code": "10-4",
          "process_category" : 10
        },
        {
          "task_code": "12-2",
          "process_category" : 10
        },
        {
          "task_code": "26-2",
          "process_category" : 1
        },
        {
          "task_code": "26-3",
          "process_category" : 1
        },
        {
          "task_code": "34-1",
          "process_category": 1
        },
        {
          "task_code": "34-17",
          "process_category": 1
        },
        {
          "task_code": "38-1",
          "process_category": 1
        },
        {
          "task_code": "40-5",
          "process_category": 1
        },
        {
          "task_code": "40-10",
          "process_category": 1
        },
        {
          "task_code": "40-11",
          "process_category": 1
        },
        {
          "task_code": "47-1",
          "process_category": 5
        },
        {
          "task_code": "47-2",
          "process_category": 1
        },
        {
          "task_code": "49-1",
          "process_category": 1
        },
        {
          "task_code": "49-2",
          "process_category": 1
        }
      ]
    },
    { 
      "level" : 3,
      "name" : "비상 대응",
      "situation": "○ 지자체 내 신종감염병 유행",
      "guideline" : "초기대응 대응지침 유지에 더해\n○ 모든 협조체계 가동\n○ 대응역량 총동원\n○ (필요시) 집단 시설 격리소 확보",

      "crisis_alert": ["경계", "심각"],
      "tasks":[
        {
          "task_code": "4-1",
          "process_category" : 0
        },
        {
          "task_code": "4-2",
          "process_category" : 1
        },
        {
          "task_code": "5-1",
          "process_category": 2
        },
        {
          "task_code": "5-2",
          "process_category": 3
        },
        {
          "task_code": "6-1",
          "process_category": 4
        },
        {
          "task_code": "7-5",
          "process_category": 1
        },
        {
          "task_code": "7-6",
          "process_category": 1
        },
        {
          "task_code": "13-3",
          "process_category": 1
        },
        {
          "task_code": "13-4",
          "process_category": 5
        },
        {
          "task_code": "13-5",
          "process_category": 5
        },
        {
          "task_code": "14-2",
          "process_category": 5
        },
        {
          "task_code": "14-4",
          "process_category": 1
        },
        {
          "task_code": "21-8",
          "process_category": 6
        },
        {
          "task_code": "41-2",
          "process_category": 1
        },
        {
          "task_code": "47-1",
          "process_category": 1
        },
        {
          "task_code": "47-2",
          "process_category": 6
        },
        {
          "task_code": "48-1",
          "process_category": 6
        },
        {
          "task_code": "49-1",
          "process_category": 1
        },
        {
          "task_code": "49-2",
          "process_category": 11
        },
        {
          "task_code": "50-1",
          "process_category": 1
        }
      ]
    },
    { 
      "level" : 4,
      "name" : "수습 복구",
      "situation": "○ 감염병 유행 및 발생 종료",
      "guideline" : "○ 발생동향 모니터링 유지\n○ 대응 평가\n○ 피해보상 및 지원",
      "crisis_alert": ["관심"],
      "tasks": [
        {
          "task_code": "14-2",
          "process_category": 1
        },
        {
          "task_code": "14-4",
          "process_category": 1
        },
        {
          "task_code": "26-7",
          "process_category": 4
        },
        {
          "task_code": "47-1",
          "process_category": 4
        },
        {
          "task_code": "47-2",
          "process_category": 1
        },
        {
          "task_code": "47-4",
          "process_category": 1
        }
      ]
    }
  ],
  "process" : [
    "상황실", "긴급생활안정지원", "긴급통신지원", "시설피해의 응급복구", "에너지 공급 피해시설 복구",
    "재난관리자원지원", "교통대책", "의료 및 방역서비스 지원", "재난현장 환경정비", "자원봉사 지원 및 관리", 
    "사회질서 유지", "재난지역 수색, 구조 및 구급지원", "재난수습 홍보"
  ],
  "task_list": {
    "1-1": {
      "title" : "징후 접수",
      "dept":{
        "main" : "보건행정과",
        "support" : "",
        "collaborate" : ""
      },
      "contents": [
        {
          "title" : "서구보건소 보건행정과 감염병관리팀수",
          "content" : [
            {
              "type" : "text",
              "source" : {
                "1" : "○ 질병관리본부 “주간 감염병 동향”(http://cdc.go.kr)을 통하거나,  또는 질병관리본부의 공문을 통해 해외 신종감염병 발생사실 인지",
                "2" : "○ 최초 접수 및 파악",
                "3" : "- 의료기관, 보건소 담당자, 지자체, 검역소, 국제보건기구(WHO, WPRO)",
                "4" : "○ 접수기관 : 서구보건소 보건행정과 감염병관리팀",
                "5" : "○ 위기징후포착 및 위기상황을 접수받은 경우, 상황파악 후 동사항을 광주광역시 → 질병관리본부장에게 보고"
              }
            },
            {
              "type" : "table",
              "source" :{
                "sub_title" : "서구보건소 보건행정과 감염병관리팀",
                "column_name" : ["소속", "전화번호"],
                "rows" : [
                   ["OO시 OO구 보건소 보건행정과", "000-000-0000"],
                   ["OO시 OO구 보건소 보건행정과", "000-000-0000"]
                 ]
              }
            }
          ]
        },
        {
          "title" : "접수 시 확인사항",
          "content" : [
            {
              "type" : "text",
              "source" : {
                "1" : "○ 해외 신종감염병 유행여부 확인",
                "2" : "○ 국내의 원인불명 감염환자 발생여부 확인"
              }
            }
          ]
        }
      ]
    },
    "2-1":{
      "title": "징후전파",
      "dept":{
        "main" : "보건행정과",
        "support" : "안전총괄과",
        "collaborate" : ""
      },
      "contents": [
        {
          "title" : "전파시간: 72시간 내",
          "content" : []
        },
        {
          "title" : "전파대상",
          "content" : [
            {
              "type" : "table",
              "source" :{
                "sub_title" : "소관부서",
                "column_name" : ["소속", "성명", "전화번호", "휴대폰번호"],
                "rows" : [
                   ["OO시 OO구 안전도시국 안전총괄과", "주OO", "000-000-0000", ""],
                   ["OO시 OO구 안전도시국 안전총괄과", "주OO", "000-000-0000", ""]
                 ]
              }
            },
            {
              "type" : "table",
              "source" : {
                "sub_title" : "필요시 유관기관에 전파",
                "column_name" : ["소속", "전화번호", "팩스번호"],
                "rows" : [
                   ["서부경찰서 경비과", "000-000-0000", "000-000-0000", ""],
                   ["서부소방서 119 재난대응과", "000-000-0000", "000-000-0000", ""],
                   ["보건환경연구원 감염병조사과", "000-000-0000", "000-000-0000", ""],
                   ["OO구 의사회 OO구 의사협회", "000-000-0000", "000-000-0000", ""],
                   ["OO구 약사회 OO구 약사협회", "000-000-0000", "000-000-0000", ""],
                   ["지역응급의료센터 서광병원", "000-000-0000", "000-000-0000", ""]
                 ]
              }
            }
          ]
        },
        {
          "title" : "전파내용",
          "content" : [
            {
              "type" : "text",
              "source" : {
                "1" : "○ 국내외 발생상황 모니터링 및 동향보고",
                "2" : "○ 타 시 ‧ 도 감염병 발생 현황",
                "3" : "○ 해외 감염병 유행현황",
                "4" : " - 유행국가, 사망인원, 유행양상 등"
              }
            }
          ]
        },
        {
          "title" : "전파방법 : 공문발송",
          "content" : [
            {
              "type" : "text",
              "source":{
                "1" : "※ 단, 긴급사항의 경우 선 구두보고 및 관련기관 전파"
              }
            }
          ]
        }
      ]
    },
    "2-2" : {"title":"징후 보고", "dept":{}, "contents":[]},
    "3-2" : {"title":"긴급대응조치", "dept":{}, "contents":[]},
    "20-1" : {"title":"방재자원 확보 현황 파악", "dept":{}, "contents":[]},
    "47-1" : {"title":"언론 모니터링 및 오보 대응", "dept":{}, "contents":[]},
    "4-1" : {"title":"상황 접수", "dept":{}, "contents":[]},
    "5-1" : {"title":"상황 보고", "dept":{}, "contents":[]},
    "5-2" : {"title":"상황 전파", "dept":{}, "contents":[]},
    "7-5" : {"title":"상황판단회의 개최", "dept":{}, "contents":[]},
    "7-6" : {"title" : "관계기관 대책 회의 준비 및 개최(필요시)", "dept": {}, "contents" : [] },
    "4-2" : {"title":"상황 파악", "dept":{}, "contents":[]},
    "6-1" : {"title":"현장 출동 지시 및 요청", "dept":{}, "contents":[]},
    "49-1" : {"title":"자가격리 모니터링", "dept":{}, "contents":[]},
    "47-2" : {"title":"보도자료 작성 및 배포", "dept":{}, "contents":[]},
    "49-2" : {"title":"접촉자 생활지원", "dept":{}, "contents":[]},
    "26-2" : {"title":"의료 및 방역 인력, 물품 파악 및 지원", "dept":{}, "contents":[]},
    "26-3" : {"title":"지자체 의약품, 방역물품 확보 및 운영", "dept":{}, "contents":[]},
    "34-1" : {"title":"격리자 폐기물 수거봉투 배급", "dept":{}, "contents":[]},
    "34-17" : {"title":"쓰레기 지원체계 가동", "dept":{}, "contents":[]},
    "10-4" : {"title":"콜센터 설치 운영", "dept":{}, "contents":[]},
    "12-2" : {"title":"특별교부세 지원사항 파악", "dept":{}, "contents":[]},
    "38-1" : {"title":"접촉자관리 지원", "dept":{}, "contents":[]},
    "40-5" : {"title":"대피명령지시", "dept":{}, "contents":[]},
    "40-10" : {"title":"안전취약계층의 특성별 대피시 고려사항", "dept":{}, "contents":[]},
    "40-11" : {"title":"안전취약계층 대피계획 수립 및 대피", "dept":{}, "contents":[]},
    "50-1" : {"title":"집단시설 격리소 확보", "dept":{}, "contents":[]},
    "48-1" : {"title":"현장 브리핑 및 취재지원", "dept":{}, "contents":[]},
    "13-3" : {"title":"임시/합동분향소 설치 운영", "dept":{}, "contents":[]},
    "13-4" : {"title":"유가족 지원 대책", "dept":{}, "contents":[]},
    "13-5" : {"title":"장례비 지원", "dept":{}, "contents":[]},
    "14-2" : {"title":"피해 보상 접수", "dept":{}, "contents":[]},
    "14-4" : {"title":"피해 보상 지원", "dept":{}, "contents":[]},
    "21-8" : {"title":"응급복구 수습 예산 지원", "dept":{}, "contents":[]},
    "41-2" : {"title":"출입통제(Police line)", "dept":{}, "contents":[]},
    "47-4" : {"title":"브리핑 및 취재지원", "dept":{}, "contents":[]},
    "26-7" : {"title":"이재민, 피해자 및 유가족 심리치료", "dept":{}, "contents":[]}
  },
  "intro": {
    "type" : "single",
    "contents": [
      {
        "title" : "목적",
        "content" : [
          {
            "type" : "text",
            "source" : {
              "1" : "이 매뉴얼은 ｢감염병의 예방 및 관리에 관한 법률｣에 따른 감염병의 확산으로 인해 공중보건위기 발생이 예상되거나 발생한 경우에 대한 신속한 대처로 감염병 확산 및 피해를 최소화하기 위하여 광주광역시 서구의 세부 대응절차 및 행동조치사항 등을 규정한 것임"
            }
          }
        ]
      },
      {
        "title" : "적용범위",
        "content" : [
          {
            "type" : "text",
            "source" : {
              "1" : "가. 감염병 재난관리 업무와 관련되는 모든 정부 부처·기관의 활동에 적용하며 보건복지부가 재난관리주관기관의 역할 수행",
              "2" : "나.「감염병의 예방 및 관리에 관한 법률」에 따른 감염병의 확산으로 인한 다음의 상황에 적용",
              "3" : "1) 해외 신종감염병이 공항 항만 등을 통해 국내 유입, 확산되는 경우",
              "4" : "인플루엔자 인체감염증, 신종인플루엔자, 에볼라바이러스병, 신종감염병증후군 등",
              "5" : "- 자체위기평가회의에서 국가 위기관리가 필요하다고 판단한 감염병",
              "6" : "2) 국내에서 원인불명 재출현 감염병이 발생 및 확산되어 자체 위기평가회의에서 국가 위기대응이 필요하다고 판단한 감염병",
              "7" : "3) 기타 위기 유형에 준하는 사항으로서 자체 위기평가회의에서 국가 위기대응이 필요하다고 판단되는 경우",
              "8" : "* 국내 상시발생 감염병이 통상적인 범위를 벗어나 대규모로 유행하여 전사회적 혼란 우려가 있다고 자체 위기평가회의에서 판단한 경우 등"
            }
          }
        ]
      },
      {
        "title" : "관련법규",
        "content" : [
          {
            "type" : "text",
            "source" : {
              "1" : "가. 감염병 대응 관련",
              "2" : "1) 감염병의 예방 및 관리에 관한 법률(보건복지부)",
              "3" : "2) 보건의료기본법(보건복지부)",
              "4" : "3) 검역법(보건복지부)",
              "5" : "4) 의료법(보건복지부)",
              "6" : "5) 감염병 재난 위기관리 표준매뉴얼(보건복지부)",
              "7" : "6) 감염병 재난 위기대응 실무매뉴얼(보건복지부)",
              "8" : "7) 메르스 대응지침(질병관리본부)",
              "9" : "8) AI 인체감염 예방 및 관리지침(질병관리본부)",
              "10" : "9) 사스(SARS) 관리지침(질병관리본부)",
              "11" : "10) 에볼라바이러스병 대응지침(질병관리본부)",
              "12" : "11) 신종인플루엔자 대유행 대비·대응 계획, 신종인플루엔자A(H1N1) 예방 및 관리지침",
              "13" : "12) 자제위기평가회의에서 국가 위기관리가 필요하다고 판단한 해당 감염병에 대한 지침",
              "14" : "13) 군중모임행사 시 감염병 관리 가이드라인",
              "15" : "14) 학생 감염병 예방·위기 대응 매뉴얼(교육부)",
              "16" : " ",
              "17" : "나. 재난 및 안전관리 관련",
              "18" : "1) 자연재해대책법(행정안전부)",
              "19" : "2) 민방위기본법(행정안전부)",
              "20" : "3) 재난 및 안전관리 기본법(행정안전부)",
              "21" : "4) 다중이용업소의 안전관리에 관한 특별법(행정안전부)",
              "22" : "5) 119구조·구급에 관한 법률(행정안전부)",
              "23" : "6) 응급의료에 관한 법률(보건복지부)",
              "24" : "7) 대기환경보전법(환경부)",
              "25" : "8) 수질 및 생태계 보전에 관한 법률(환경부)",
              "26" : " ",
              "27" : "다. 기타",
              "28" : "1) 국가위기관리기본지침(대통령훈령 제388호)",
              "29" : "2) 사회재난 관련 중앙재난안전대책본부의 구성 및 운영에 관한 규정 (대통령훈령 제402호)",
              "30" : " ",
              "31" : "라. 자치 법규",
              "32" : "1) 광주광역시 감염병의 예방 및 관리 조례",
              "33" : "2) 광주광역시 재난대책본부 운영 조례"
            }
          }
        ]
      },
      {
        "title" : "용어정리",
        "content" : [
          {
          "type" : "table",
            "source" :{
              "sub_title" : "",
              "column_name" : ["용어", "정의"],
              "rows" : [
                  ["국가위기", "국가 주권, 영토와 국민의 생명·재산 등 국가의 핵심요소와 가치에 중대한 위해가 가해질 가능성이 있거나 가해지고 있는 상태"],
                  ["위기관리", "국가위기를 효과적으로 예방ㆍ대비하고 대응ㆍ복구하기 위하여 국가가 자원을 기획ㆍ조직ㆍ집행ㆍ조정ㆍ통제하는 제반 활동과정"],
                  ["비상상황", "대규모 피해 발생 우려로 일상적 대응보다 훨씬 강화된 조치나 특별한 의사결정이 요구되는 상황. 비상상황은 진행양상과 대처내용에 따라 결과수습형, 완만진행형, 순간증폭형으로 구분"],
                  ["결과수습형", "상황 발생 자체가 이미 대규모 피해로 나타난 유형"],
                  ["완만진행형", "상황이 서서히 진행되면서 심각성도 점차적으로 증가하는 유형"],
                  ["순간증폭형", "발생 초기에는 저강도 비상상황으로 보여지나, 진행과정에서 심각한 상황으로 급변하면서 대응력의 한계가 노정되고 실패 시 중대재난으로 귀결되는 유형"],
                  ["재난관리 주관기관", "재난이나 그 밖의 각종 사고에 대하여 그 유형별로 예방·대비·대응·복구 등의 업무를 주관하여 수행하는 기관"],
                  ["유관기관", "해당 재난에 대한 정부의 재난관리 활동에 있어 주관기관의 활동을 지원하고 협조하는 중앙행정기관 및 그 소속기관"],
                  ["실무기관", "재난관리의 대상이 되는 기능·시설을 직접 관리하거나 그 지역을 관할하는 지방자치단체, 공공기관 및 단체"],
                  ["감염", "감염병의 병원체가 사람의 몸에 침입하여 질병을 유발하는 모든 경우를 통칭함"],
                  ["신종ㆍ재출현 감염병", "기존에 알려지지 않은 새로운 감염병 및 과거에 사라졌다가 다시 발생한 감염병"],
                  ["해외유입 감염병", "현재까지 우리나라에서 자체적으로 발생하지는 않았으나 해외에서 국내 유입이 가능하거나 우리나라 국민들이 해외에서 감염될 가능성이 있는 각종 감염병"],
                  ["인수공통 감염병", "동물과 사람 간에 서로 전파되는 병원체에 의하여 발생되는 감염병 중 보건복지부장관이 고시하는 감염병"],
                  ["감염병 환자", "감염병의 병원체가 인체에 침입하여 증상을 나타내는 사람으로서 감염병의 예방 및 관리에 관한 법률 제11조제6항의 진단 기준에 따른 의사 또는 한의사의 진단이나 보건복지부령이 정하는 기관의 실험실 검사를 통하여 확인된 사람"],
                  ["감염병 의사환자", "감염병의 병원체가 인체에 침입한 것으로 의심이 되나 감염병환자로 확인되기 전 단계에 있는 사람"],
                  ["병원체 보유자", "임상적인 증상은 없으나 감염병의 병원체를 보유하고 있는 사람"],
                  ["환자격리", "타인의 감염을 막기 위해 감염병환자 등을 일정기간 감염병관리기관에 입원시켜 외부인과의 접촉을 차단하는 조치"],
                  ["역학조사", "감염병환자, 감염병의사환자 또는 병원체보유자(이하 감염병환자등이라 한다)가 발생한 경우 감염병의 차단과 확산방지 등을 위하여 감염병환자등의 발생 규모를 파악하고 감염원을 추적하는 등의 활동과 감염병 예방접종 후 이상반응 사례가 발생한 경우 그 원인을 규명하기 위하여 하는 활동"],
                  ["검역", "해외유입 감염병에 대한 예방 및 조기 발견의 수단으로 공항과 항만에서 사람, 항공기, 선박, 자동차, 화물 등을 검사ㆍ격리ㆍ방역하는 등의 위생조치를 취하는 일련의 활동"],
                  ["방역물자", "방역업무 수행에 필요한 보호장구, 소독약품, 진단시약, 검사장비 등 모든 물품을 통칭함"],
                  ["제한적 전파", "전파 양상이 특정 공간(의료기관, 학교, 직장, 집단 시설 등) 위주로 역학적 연관성을 유지하는 경우"],
                  ["지역사회 전파", "전파 양상이 특정 공간을 넘어 역학적 연관성이 불분명한 사례가 다수 발생하는 경우"],
                  ["전국적 확산", "전파 양상이 전국적이며 역학적 연관성을 추적하는 것이 방역 대책에 있어 우선순위가 아닌 경우"]
              ]
            }
          }
        ]
      }
    ]
  },
  "risk_alert":{
    "type" : "single",
    "contents": [
      {
        "title" : "",
        "content" : [
          {
          "type" : "table",
            "source" :{
              "sub_title" : "",
              "column_name" : ["구분", "판단기준", "비고"],
              "rows" : [
                ["관심(blue)", "[해외 신종 감염병]\n○ 해외에서의 신종감염병의 발생 및 유행\n[국내 원인불명·재출현 감염병]\n○ 국내 원인불명·재출현 감염병의 발생\n", "○ 감염병별 대책반 운영(질본)\n○ 위기징후 모니터링 및 감시\n○ 대응 역량 정비\n○ 필요시 현장 방역 조치 및 방역 인프라 가동"],
                ["주의(yellow)", "[해외 신종 감염병]\n○ 해외에서의 신종감염병의 발생 및 유행\n[국내 원인불명·재출현 감염병]\n○ 국내 원인불명·재출현 감염병의 발생\n", "○ 감염병별 대책반 운영(질본)\n○ 위기징후 모니터링 및 감시\n○ 대응 역량 정비\n○ 필요시 현장 방역 조치 및 방역 인프라 가동"],
                ["경계(orange)", "[해외 신종 감염병]\n○ 해외에서의 신종감염병의 발생 및 유행\n[국내 원인불명·재출현 감염병]\n○ 국내 원인불명·재출현 감염병의 발생\n", "○ 감염병별 대책반 운영(질본)\n○ 위기징후 모니터링 및 감시\n○ 대응 역량 정비\n○ 필요시 현장 방역 조치 및 방역 인프라 가동"],
                ["심각(red)", "[해외 신종 감염병]\n○ 해외에서의 신종감염병의 발생 및 유행\n[국내 원인불명·재출현 감염병]\n○ 국내 원인불명·재출현 감염병의 발생\n", "○ 감염병별 대책반 운영(질본)\n○ 위기징후 모니터링 및 감시\n○ 대응 역량 정비\n○ 필요시 현장 방역 조치 및 방역 인프라 가동"]
              ]
            }
          }
        ]
      }
    ]
  },
  "process_flow" :{
    "type" : "select_box",
    "contents": [
      {
        "title" : "위기 형태",
        "content" : [
          {
            "type" : "text",
            "source" : {
              "1" : "가. 원인",
              "2" : "1) 해외 신종감염병의 국내 유입 및 확산",
              "3" : "2) 국내 원인불명ㆍ재출현 감염병 등의 발생 및 확산",
              "4" : "3) 기타 위기 유형에 준하는 사항으로서 자체 위기평가회의에서",
              "5" : "국가 감염병 위기 대응이 필요하다고 판단되는 경우"
            }
          },
          {
            "type" : "table",
            "source" :{
              "sub_title" : "나. 전개양상",
              "column_name" : ["위기징후", "위기상황 전개", "국가위기로 발전", "해소"],
              "rows" : [
                [
                  "◈ 해외에서의 신종감염병 발생\n◈ 국내 원인불명·재출현 감염병 발생\n◈ 그 외 위기평가회의에서 대응이 필요하다고 판단한 감염병의 발생",
                "◈ 해외 신종감염병 국내 유입 및 확산\n◈ 국내 원인불명·재출현 감염병 확산\n◈ 그 외 위기평가회의에서 대응이 필요하다고 판단한 감염병의 확산",
                "◈ 감염병의 전국적 확산\n◈ 감염병 환자 및 사망자 증가\n◈ 광범위한 사회경제적 손실 초래\n◈ 국가 이미지 실추에 따른 국가경쟁력 저하",
                "◈ 환자 및 사망자 감소\n◈ 추가 전파 차단\n◈ 유행 종식"
                ]
              ]
            }
          }
        ]
      } 
    ]
  },
  "emergency_contact" :[
    {
      "title" : "질병관리청",
      "column_name" : ["소속", "직위", "성명", "전화번호", "팩스번호", "휴대폰번호", "이메일", "관리"],
      "contents":[
        ["질병관리청상황실", "", "상황실", "000-000-0000","000-000-0000", "", "", ""]
      ]
    },
    {
      "title" : "OO시",
      "column_name" : ["소속", "직위", "성명", "전화번호", "팩스번호", "휴대폰번호", "이메일", "관리"],
      "contents":[
        ["OO시 재난안전상황실", "", "감OO", "000-000-0000", "000-000-0000", "", "", ""],
        ["OO시 재난안전상황실", "", "감OO", "000-000-0000","000-000-0000", "", "", ""],
        ["OO시 재난안전상황실", "", "감OO", "000-000-0000", "000-000-0000", "", "", ""],
        ["OO시 재난안전상황실", "", "감OO", "000-000-0000", "000-000-0000", "", "", ""],
        ["OO시 재난안전상황실", "", "감OO", "000-000-0000", "000-000-0000", "", "", ""]
      ]
    },
    {
      "title" : "OO구",
      "column_name" : ["소속", "직위", "성명", "전화번호", "팩스번호", "휴대폰번호", "이메일", "관리"],
      "contents":[
        ["OO시 재난안전상황실", "", "감OO", "000-000-0000", "000-000-0000", "", "", ""],
        ["OO시 재난안전상황실", "", "감OO", "000-000-0000", "000-000-0000", "", "", ""],
        ["OO시 재난안전상황실", "", "감OO", "000-000-0000", "000-000-0000", "", "", ""],
        ["OO시 재난안전상황실", "", "감OO", "000-000-0000", "000-000-0000", "", "", ""],
        ["OO시 재난안전상황실", "", "감OO", "000-000-0000", "000-000-0000", "", "", ""]
      ]
    },
    {
      "title" : "유관기관",
      "column_name" : ["소속", "직위", "성명", "전화번호", "팩스번호", "휴대폰번호", "이메일", "관리"],
      "contents":[
        ["서부경찰서 경비과", "", "감OO", "000-000-0000", "000-000-0000", "", "", ""],
        ["서부소방서 119 재난대응과", "", "감OO", "000-000-0000", "000-000-0000", "", "", ""],
        ["보건환경연구원 감염병조사과", "", "감OO", "000-000-0000", "000-000-0000", "", "", ""],
        ["OO구 의사회 OO구 의사협회", "", "감OO", "000-000-0000", "000-000-0000", "", "", ""],
        ["OO구 약사회 OO구 약사협회", "", "감OO", "000-000-0000", "000-000-0000", "", "", ""]
      ]
    }
  ], 
  "docs_format" : {
    "column_name" : ["서식명", "파일명", "조치내용", "파일위치"],
    "contents": [
      ["공통-[제10호 서식] 시군구 재난안전대책본부회의 심의 안건 예시", "공통-[제10호 서식] 시군구 재난안전대책본부회의 심의 안건 예시.hwp", "13-5"],
      ["공통-[제10호 서식] 시군구 재난안전대책본부회의 심의 안건 예시", "공통-[제10호 서식] 시군구 재난안전대책본부회의 심의 안건 예시.hwp", "13-5"],
      ["공통-[제10호 서식] 시군구 재난안전대책본부회의 심의 안건 예시", "공통-[제10호 서식] 시군구 재난안전대책본부회의 심의 안건 예시.hwp", "13-5"]
    ]
  },
  "revision_history" : {
    "column_name" : ["재개정일자", "주요내용", "사유", "담당자"],
    "contents": [
      ["2017.01.19", "16.11월 행동매뉴얼 전면 개선", "개정장비", "박모씨"],
      ["2017.01.19", "16.11월 행동매뉴얼 전면 개선", "개정장비", "박모씨"],
      ["2017.01.19", "16.11월 행동매뉴얼 전면 개선", "개정장비", "박모씨"],
      ["2017.01.19", "16.11월 행동매뉴얼 전면 개선", "개정장비", "박모씨"],
      ["2017.01.19", "16.11월 행동매뉴얼 전면 개선", "개정장비", "박모씨"],
      ["2017.01.19", "16.11월 행동매뉴얼 전면 개선", "개정장비", "박모씨"],
      ["2017.01.19", "16.11월 행동매뉴얼 전면 개선", "개정장비", "박모씨"]
    ]
  }
}


//! 여기서 안먹히면 kibana에서는 먹힘
### ! 다른거 control_number, name 만 추가 ======================
POST {{host}}/_bulk
content-Type: {{contentType}}

###
POST {{host}}/_bulk
content-Type: {{contentType}}

{ "create" : { "_index" : "disaster" } }
{"control_number" : 2, "name": "가뭄" }
{ "create" : { "_index" : "disaster" } }
{"control_number" : 3, "name": "풍수해" }
{ "create" : { "_index" : "disaster" } }
{"control_number" : 4, "name": "지진" }
{ "create" : { "_index" : "disaster" } }
{"control_number" : 5, "name": "대형화산폭발" }
{ "create" : { "_index" : "disaster" } }
{"control_number" : 6, "name": "산사태" }
{ "create" : { "_index" : "disaster" } }
{"control_number" : 7, "name": "한파" }
{ "create" : { "_index" : "disaster" } }
{"control_number" : 8, "name": "산불" }
{ "create" : { "_index" : "disaster" } }
{"control_number" : 9, "name": "유해화학물질 유출사고" }
{ "create" : { "_index" : "disaster" } }
{"control_number" : 10, "name": "대규모 수질오염" }
{ "create" : { "_index" : "disaster" } }
{"control_number" : 11, "name": "다중밀집시설 대형화재" }
{ "create" : { "_index" : "disaster" } }
{"control_number" : 12, "name": "다중밀집건축물 붕괴 대형사고" }
{ "create" : { "_index" : "disaster" } }
{"control_number" : 13, "name": "가축질병" }
{ "create" : { "_index" : "disaster" } }
{"control_number" : 14, "name": "정보통신사고" }
{ "create" : { "_index" : "disaster" } }
{"control_number" : 15, "name": "원전안전" }
{ "create" : { "_index" : "disaster" } }
{"control_number" : 16, "name": "전력" }
{ "create" : { "_index" : "disaster" } }
{"control_number" : 17, "name": "보건의료" }
{ "create" : { "_index" : "disaster" } }
{"control_number" : 18, "name": "육상화물운송" }
{ "create" : { "_index" : "disaster" } }
{"control_number" : 19, "name": "저수지붕괴" }
{ "create" : { "_index" : "disaster" } }
{"control_number" : 20, "name": "경기장 및 공연장 안전사고" }
{ "create" : { "_index" : "disaster" } }
{"control_number" : 21, "name": "가스분야" }


### ! 특정 필드만 선택해서 가져오기
GET {{host}}/disaster/_search
{ 
"fields": ["control_number", "name"],
"_source": false,
"size" : 100 
}